
// Controllers

angular.module('c4p.controllers', [
'crtl.responsive',
'crtl.navigation',
'crtl.action',
'crtl.aside',
'crtl.asideItem',
'crtl.asideSearch',
'crtl.calendar',
'crtl.config',
'crtl.detail',
'crtl.detailedObject',
'crtl.detailLink',
'crtl.detailLinkedObjects',
'crtl.dragObject',
'crtl.editFocus',
'crtl.inlinedObject',
'crtl.linkActions',
'crtl.meeting',
'crtl.meetingAttendeeDrag',
'crtl.meetingAttendeeDrop',
'crtl.meetingElementDrag',
'crtl.meetingElementDrop',
'crtl.meetingEmail',
'crtl.meetingObjLinkDrop',
'crtl.meetingRemoveDrop',
'crtl.namedObject',
'crtl.navObject',
'crtl.networkTestRunner',
'crtl.rightToolbar',
'crtl.singleTap',
'crtl.summarizedObject',
//'crtl.timeline',
'crtl.trashObject',
'crtl.viewer'
]);
